FROM php:8.2-cli

WORKDIR /app

COPY . .

RUN apt-get update && apt-get install -y zip unzip curl \
    && curl -sS https://getcomposer.org/installer | php \
    && php composer.phar install --no-dev

EXPOSE 8000

CMD php artisan serve --host=0.0.0.0 --port=8000
